sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
    #配置redis数据源
  redis:
    host: localhost
    port: 6379
    password: root
    database: 0
    #微信小程序配置
  wechat:
    appid: wx762caba6da70cece
    secret: 0159a33fb4a7c718fd5e272a612b5e90
#    mchid: 1561414331   #商户号
#    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606  #证书序列号
#    privateKeyFilePath: D:\apiclient_key.pem  #私钥文件（需要更改）
#    apiV3Key: CZBK51236435wxpay435434323FFDuv3   #解密密钥
#    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem #(平台证书文件)
#    notifyUrl: https://1d727b0b.r21.cpolar.top/notify/paySuccess #/后台controller请求访问的路径    #支付成功之后的回调
#    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php #/后台controller请求访问的路径  # 用户退款成功之后的回调  这两个临时域名是一次性的，需要用内网穿透工具获取最新的域名并进行更改

  #阿里云相关配置
  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com  #访问域名
    access-key-id: LTAI5t6v5j2CxnUcFJJgzjxz #标识用户
    access-key-secret: 5g7ha7fWasPJ87EVuFkxobWWwFzX8u #验证用户的密钥
    bucket-name: sky-take-out-zqm #存储地方


